export interface ApiMethodSchema {
  name: string;
  params: Record<string, string>;
}

export interface ApiSchema {
  protocolVersion: number;
  schemaVersion: number;
  transport: "newline-delimited-json";
  methods: ApiMethodSchema[];
}

export const apiSchema: ApiSchema = {
  protocolVersion: 1,
  schemaVersion: 2,
  transport: "newline-delimited-json",
  methods: [
    method("hello"),
    method("ping"),
    method("state.get"),
    method("agent.manifests"),
    method("agent.list"),
    method("agent.get", { target: "string" }),
    method("agent.send", { paneId: "string", text: "string" }),
    method("task.get", { paneId: "string" }),
    method("task.changes", { paneId: "string" }),
    method("task.update", { paneId: "string", patch: "object", source: "string?", expectedRevision: "number?" }),
    method("agent.read", { target: "string", rows: "number?" }),
    method("marketplace.refresh"),
    method("worktree.list", { root: "string?" }),
    method("worktree.create", {
      root: "string",
      path: "string",
      branch: "string",
      createBranch: "boolean?",
      startPoint: "string?",
    }),
    method("worktree.open", { path: "string", name: "string?" }),
    method("worktree.remove", {
      root: "string",
      path: "string",
      force: "boolean?",
    }),
    method("tab.create", { name: "string?" }),
    method("tab.select", { tabId: "string" }),
    method("tab.close", { tabId: "string" }),
    method("tab.rename", { tabId: "string", name: "string" }),
    method("tab.list"),
    method("tab.focus", { tabId: "string" }),
    method("workspace.create", { name: "string?" }),
    method("workspace.select", { workspaceId: "string" }),
    method("workspace.close", { workspaceId: "string" }),
    method("workspace.rename", { workspaceId: "string", name: "string" }),
    method("workspace.list"),
    method("workspace.get", { workspaceId: "string" }),
    method("workspace.focus", { workspaceId: "string" }),
    method("pane.create", {
      direction: '"right"|"down"?',
      command: "string?",
      cwd: "string?",
      title: "string?",
      focus: "boolean?",
    }),
    method("pane.focus", { paneId: "string" }),
    method("pane.rename", { paneId: "string", title: "string" }),
    method("pane.zoom", { paneId: "string", zoomed: "boolean?" }),
    method("pane.swap", {
      paneId: "string?",
      targetPaneId: "string?",
      direction: "string?",
    }),
    method("pane.focus_direction", { direction: "string", paneId: "string?" }),
    method("pane.neighbor", { direction: "string", paneId: "string?" }),
    method("pane.move", { paneId: "string", targetTabId: "string" }),
    method("client.window_title", { title: "string?" }),
    method("pane.report_metadata", { paneId: "string", source: "string" }),
    method("workspace.report_metadata", {
      workspaceId: "string",
      source: "string",
      tokens: "object",
    }),
    method("agent.view.set", { view: "object" }),
    method("agent.view.clear", { source: "string?" }),
    method("pane.move_new", {
      paneId: "string",
      destination: "string",
      workspaceId: "string?",
      label: "string?",
      tabLabel: "string?",
    }),
    method("pane.resize-layout", { paneId: "string", delta: "number" }),
    method("pane.input", { paneId: "string", data: "string" }),
    method("pane.paste", { paneId: "string", text: "string" }),
    method("surface.subscribe", { panes: "array" }),
    method("surface.scroll", { paneId: "string", lines: "number" }),
    method("server.reload_config"),
    method("server.live_handoff"),
    method("pane.report_agent", {
      paneId: "string",
      source: "string",
      agent: "string",
      state: "string",
      ttlMs: "number?",
    }),
    method("pane.release_agent", { paneId: "string", source: "string?" }),
    method("pane.link_at", { paneId: "string", line: "number", col: "number" }),
    method("integration.list"),
    method("integration.install", { target: "string" }),
    method("integration.uninstall", { target: "string" }),
    method("pane.report_agent_session", {
      paneId: "string",
      source: "string",
      agent: "string",
      sessionId: "string",
    }),
    method("agent.explain", { target: "string" }),
    method("notification.show", {
      title: "string",
      body: "string?",
      position: "string?",
      sound: "string?",
    }),
    method("command.run", { command: "string", commandType: "string" }),
    method("popup.close", { paneId: "string?" }),
    method("pane.edit_scrollback", { paneId: "string" }),
    method("surface.scroll_to", { paneId: "string", top: "number?" }),
    method("pane.text", { paneId: "string", start: "number", count: "number" }),
    method("pane.search", {
      paneId: "string",
      query: "string",
      line: "number",
      col: "number",
      direction: "string",
    }),
    method("tab.move", { tabId: "string", insertIndex: "number" }),
    method("workspace.move", { workspaceId: "string", insertIndex: "number" }),
    method("pane.clear", { paneId: "string" }),
    method("pane.focus-report", { paneId: "string", focused: "boolean" }),
    method("pane.mouse", {
      paneId: "string",
      col: "number",
      row: "number",
      button: "string",
      action: "string",
    }),
    method("pane.resize", {
      paneId: "string?",
      cols: "number?",
      rows: "number?",
      direction: "string?",
      amount: "number?",
    }),
    method("pane.scroll", { paneId: "string", lines: "number" }),
    method("pane.close", { paneId: "string" }),
    method("pane.list"),
    method("pane.current"),
    method("pane.get", { paneId: "string" }),
    method("pane.split", {
      direction: '"right"|"down"?',
      command: "string?",
      cwd: "string?",
      title: "string?",
    }),
    method("pane.read", {
      paneId: "string",
      rows: "number?",
      source: '"visible"|"recent"|"recent-unwrapped"?',
    }),
    method("pane.send_text", { paneId: "string", text: "string" }),
    method("pane.send_keys", { paneId: "string", keys: "string" }),
    method("clipboard.write", { text: "string" }),
    method("layout.export", { tabId: "string?" }),
    method("layout.apply", { tabId: "string?", layout: "LayoutNode" }),
    method("pane.snapshot", {
      paneId: "string",
      rows: "number",
      source: '"visible"|"recent"|"recent-unwrapped"?',
    }),
    method("pane.wait", {
      paneId: "string",
      statuses: "AgentStatus[]",
      timeoutMs: "number?",
    }),
    method("server.stop"),
    method("plugin.link", { path: "string" }),
    method("plugin.unlink", { pluginId: "string" }),
    method("plugin.set-enabled", { pluginId: "string", enabled: "boolean" }),
    method("plugin.action-invoke", {
      pluginId: "string",
      actionId: "string",
      context: "object?",
    }),
    method("plugin.uninstall", { pluginId: "string" }),
    method("plugin.config-dir", { pluginId: "string" }),
    method("plugin.log-list", { pluginId: "string?", limit: "number?" }),
    method("plugin.pane-open", {
      pluginId: "string",
      entrypointId: "string",
      placement: "overlay|popup|split|tab|zoomed?",
      width: "number|string?",
      height: "number|string?",
      workspaceId: "string?",
      targetPaneId: "string?",
      direction: "right|down?",
      cwd: "string?",
      focus: "boolean?",
      env: "object?",
    }),
    method("plugin.pane-focus", { paneId: "string" }),
    method("plugin.pane-close", { paneId: "string" }),
    method("plugin.link-open", { url: "string", paneId: "string?" }),
    method("machine.refresh", { labelOrId: "string" }),
    method("machine.agent-get", { labelOrId: "string", target: "string" }),
    method("machine.pane-read", {
      labelOrId: "string",
      paneId: "string",
      rows: "number?",
      source: '"visible"|"recent"|"recent-unwrapped"?',
    }),
    method("machine.pane-input", {
      labelOrId: "string",
      paneId: "string",
      data: "string",
      raw: "boolean?",
    }),
    method("machine.request", {
      labelOrId: "string",
      request: "object",
      timeoutMs: "number?",
    }),
    method("machine.sync"),
    method("config.keymap"),
    method("machine.agent-read", {
      labelOrId: "string",
      target: "string",
      rows: "number?",
      source: '"visible"|"recent"|"recent-unwrapped"?',
    }),
    method("machine.agent-prompt", {
      labelOrId: "string",
      target: "string",
      prompt: "string",
      timeoutMs: "number?",
    }),
    method("events.subscribe"),
    method("events.unsubscribe"),
    method("events.wait", { event: "string?", timeoutMs: "number?" }),
  ],
};

function method(
  name: string,
  params: Record<string, string> = {},
): ApiMethodSchema {
  return { name, params };
}
