/** Builds ssh invocations for `--remote`, `machine exec`, and saved-machine
 * bridges.
 *
 * With `[remote] manage_ssh_config = true` (the default) ssh runs with
 * `-F <generated config>`. The generated file Includes the user's
 * ~/.ssh/config and the system config first, so every setting the user
 * made wins (ssh keeps the first value it reads), then adds keepalive
 * fallbacks. Connection reuse goes through a ControlMaster socket in a
 * private per-user runtime directory. */
import { createHash } from "node:crypto";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { sshTarget } from "../machines.js";

export interface SshEndpoint {
  user: string | null;
  host: string;
  port: number | null;
}

/** `shared`: one master per destination for the whole user (saved machines
 * and `machine exec` share it). `private`: a master owned by one process
 * (`--remote`). `none`: no connection reuse. */
export type ControlMode = "shared" | "private" | "none";

export interface SshOptions {
  /** `[remote] manage_ssh_config`. */
  manage: boolean;
  control: ControlMode;
  /** Never prompt (background connections). */
  batch: boolean;
  /** `-t` to force a TTY, `-T` to disable one; omitted leaves ssh's default. */
  tty?: "force" | "disable";
}

export interface SshPaths {
  configFile: string | null;
  controlPath: string | null;
}

export const KEEPALIVE_INTERVAL_SECONDS = 15;
export const KEEPALIVE_COUNT_MAX = 4;
/** Seconds a shared master lingers after its last session closes. */
export const CONTROL_PERSIST_SECONDS = 60;

export function sshProgram(env: NodeJS.ProcessEnv = process.env): string {
  return env.SHEPHERD_SSH || "ssh";
}

/** Text of the generated ssh config. `includes` are Included in order before
 * Shepherd's fallbacks. */
export function generateSshConfig(includes: string[]): string {
  const lines = [
    "# Generated by Shepherd for remote connections; rewritten on use.",
    "# Your own settings are Included first and take precedence.",
  ];
  for (const file of includes) lines.push(`Include ${quoteConfigValue(file)}`);
  lines.push(
    "",
    "Host *",
    `  ServerAliveInterval ${KEEPALIVE_INTERVAL_SECONDS}`,
    `  ServerAliveCountMax ${KEEPALIVE_COUNT_MAX}`,
    "",
  );
  return lines.join("\n");
}

/** The ssh configs a normal `ssh` would read, when they exist. `-F`
 * replaces both, so both are Included. */
export function defaultSshIncludes(
  home = os.homedir(),
  exists: (file: string) => boolean = fs.existsSync,
): string[] {
  const candidates = [
    path.join(home, ".ssh", "config"),
    process.platform === "win32"
      ? path.join(process.env.ProgramData ?? "C:\\ProgramData", "ssh", "ssh_config")
      : "/etc/ssh/ssh_config",
  ];
  return candidates
    .filter((file) => exists(file))
    .map((file) => file.replaceAll("\\", "/"));
}

/** Pure: the ssh argument vector for `endpoint`, ending with the remote
 * command when one is given. */
export function sshArguments(
  endpoint: SshEndpoint,
  remoteCommand: string | null,
  options: SshOptions,
  paths: SshPaths,
): string[] {
  const args: string[] = [];
  if (options.manage && paths.configFile) args.push("-F", paths.configFile);
  if (options.batch) args.push("-o", "BatchMode=yes");
  if (options.manage && options.control !== "none" && paths.controlPath) {
    args.push(
      "-o",
      "ControlMaster=auto",
      "-o",
      `ControlPath=${paths.controlPath}`,
      "-o",
      `ControlPersist=${CONTROL_PERSIST_SECONDS}`,
    );
  }
  if (options.tty === "force") args.push("-t");
  if (options.tty === "disable") args.push("-T");
  if (endpoint.port !== null && endpoint.port !== 22) {
    args.push("-p", String(endpoint.port));
  }
  args.push("--", sshTarget(endpoint));
  if (remoteCommand !== null) args.push(remoteCommand);
  return args;
}

/** Private per-user directory for generated configs and control sockets.
 * Kept short: control socket paths must fit in sun_path (104 bytes on
 * macOS), which rules out macOS's long $TMPDIR. */
export function sshRuntimeDirectory(env: NodeJS.ProcessEnv = process.env): string {
  if (env.SHEPHERD_SSH_RUNTIME_DIR) return path.resolve(env.SHEPHERD_SSH_RUNTIME_DIR);
  if (process.platform === "win32") return path.join(os.tmpdir(), "shepherd-ssh");
  const uid = typeof process.getuid === "function" ? process.getuid() : 0;
  return path.join("/tmp", `shepherd-ssh-${uid}`);
}

/** Creates the runtime directory 0700 and refuses one that another user
 * owns or that is a symlink (it lives in a shared /tmp). */
export function ensurePrivateDirectory(directory: string): string {
  fs.mkdirSync(directory, { recursive: true, mode: 0o700 });
  if (process.platform === "win32") return directory;
  const stat = fs.lstatSync(directory);
  const uid = typeof process.getuid === "function" ? process.getuid() : stat.uid;
  if (!stat.isDirectory() || stat.isSymbolicLink() || stat.uid !== uid) {
    throw new Error(`unsafe ssh runtime directory: ${directory}`);
  }
  if ((stat.mode & 0o077) !== 0) fs.chmodSync(directory, 0o700);
  return directory;
}

export function controlPath(directory: string, mode: ControlMode): string | null {
  if (mode === "none" || process.platform === "win32") return null;
  // %C is ssh's hash of local host, remote host, port and user.
  return mode === "shared"
    ? path.join(directory, "%C")
    : path.join(directory, `a${process.pid}-%C`);
}

/** Writes the generated config (content-addressed, so concurrent writers
 * agree) and returns its path. */
export function writeSshConfig(directory: string, contents: string): string {
  const hash = createHash("sha256").update(contents).digest("hex").slice(0, 12);
  const file = path.join(directory, `ssh_config-${hash}`);
  try {
    if (fs.readFileSync(file, "utf8") === contents) return file;
  } catch {
    // Missing or unreadable: write it below.
  }
  const temporary = `${file}.${process.pid}.tmp`;
  fs.writeFileSync(temporary, contents, { mode: 0o600 });
  fs.renameSync(temporary, file);
  return file;
}

/** Resolves paths (writing the generated config when managed) and returns
 * the program and arguments to spawn. */
export function sshInvocation(
  endpoint: SshEndpoint,
  remoteCommand: string | null,
  options: SshOptions,
): { command: string; args: string[]; paths: SshPaths } {
  let paths: SshPaths = { configFile: null, controlPath: null };
  if (options.manage) {
    const directory = ensurePrivateDirectory(sshRuntimeDirectory());
    paths = {
      configFile: writeSshConfig(directory, generateSshConfig(defaultSshIncludes())),
      controlPath: controlPath(directory, options.control),
    };
  }
  return {
    command: sshProgram(),
    args: sshArguments(endpoint, remoteCommand, options, paths),
    paths,
  };
}

/** Asks a private master to exit. Best effort; a lingering master also
 * exits by itself after ControlPersist. */
export async function closeControlMaster(
  endpoint: SshEndpoint,
  paths: SshPaths,
): Promise<void> {
  if (!paths.controlPath) return;
  const { spawn } = await import("node:child_process");
  const args = [
    ...(paths.configFile ? ["-F", paths.configFile] : []),
    "-o",
    `ControlPath=${paths.controlPath}`,
    "-O",
    "exit",
    ...(endpoint.port !== null && endpoint.port !== 22 ? ["-p", String(endpoint.port)] : []),
    "--",
    sshTarget(endpoint),
  ];
  await new Promise<void>((resolve) => {
    const child = spawn(sshProgram(), args, { stdio: "ignore" });
    const timer = setTimeout(() => {
      child.kill("SIGKILL");
      resolve();
    }, 2_000);
    child.once("error", () => {
      clearTimeout(timer);
      resolve();
    });
    child.once("exit", () => {
      clearTimeout(timer);
      resolve();
    });
  });
}

/** POSIX single-quoting for words of a remote command line. */
export function shellQuote(value: string): string {
  return /^[A-Za-z0-9_./:=@%+,-]+$/.test(value)
    ? value
    : `'${value.replace(/'/g, `'\\''`)}'`;
}

function quoteConfigValue(value: string): string {
  return /[\s"]/.test(value) ? `"${value.replaceAll('"', '\\"')}"` : value;
}
